# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e632dbcfd543086cb01a39bb639b95bf688b9414c4616185215f9a5b5dbba8245045525e041e4bf7c0f00c6eac9fb8ef63410f381ec59063fa25e0272746f39

test:
  secret_key_base: 4d0d5c5394f72aecc3ee53ec40608f1778aa8bba18e54bd0239bb6322e187a6999dfa9b53c9bfd7ac23b79a694b21dd0cc3d6d71e13dd2dce5d6438a64195ddc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
